In [40]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Numpy merupakan library python yang digunakan untuk komputasi matriks.
Matplotlib merupakan library python yang digunakan untuk presentasi data berupa grafik atau plot.

In [41]:
dataset = pd.read_csv("Data.csv")
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [42]:
print(x)

[[15624510        1       19    19000]
 [15810944        1       35    20000]
 [15668575        2       26    43000]
 [15603246        2       27    57000]
 [15804002        1       19    76000]
 [15728773        1       27    58000]
 [15598044        2       27    84000]
 [15694829        2       32   150000]
 [15600575        1       45    33000]
 [15727311        2       35    60000]
 [15570769        2       26    80000]
 [15606274        2       26    52000]
 [15746139        1       20    86000]
 [15704987        1       32    18000]
 [15628972        1       18    82000]
 [15697686        1       29    80000]
 [15733883        1       47    25000]
 [15617482        1       45    26000]
 [15704583        1       46    28000]
 [15621083        2       48    29000]
 [15649487        1       45    22000]
 [15736760        2       47    49000]
 [15714658        1       48    41000]
 [15599081        2       45    22000]
 [15705113        1       46    23000]]


In [43]:
print(y)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1]


In [44]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(x[:, 1:4])
x[:, 1:4] = imputer.transform(x[:, 1:4])

In [45]:
print(x)

[[15624510        1       19    19000]
 [15810944        1       35    20000]
 [15668575        2       26    43000]
 [15603246        2       27    57000]
 [15804002        1       19    76000]
 [15728773        1       27    58000]
 [15598044        2       27    84000]
 [15694829        2       32   150000]
 [15600575        1       45    33000]
 [15727311        2       35    60000]
 [15570769        2       26    80000]
 [15606274        2       26    52000]
 [15746139        1       20    86000]
 [15704987        1       32    18000]
 [15628972        1       18    82000]
 [15697686        1       29    80000]
 [15733883        1       47    25000]
 [15617482        1       45    26000]
 [15704583        1       46    28000]
 [15621083        2       48    29000]
 [15649487        1       45    22000]
 [15736760        2       47    49000]
 [15714658        1       48    41000]
 [15599081        2       45    22000]
 [15705113        1       46    23000]]


In [46]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# x = np.array(ct.fit_transform(x))

In [48]:
# print(x)

In [49]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [50]:
print(y)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1]


In [51]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [52]:
print(x_train)

[[15570769        2       26    80000]
 [15704583        1       46    28000]
 [15621083        2       48    29000]
 [15804002        1       19    76000]
 [15668575        2       26    43000]
 [15649487        1       45    22000]
 [15598044        2       27    84000]
 [15694829        2       32   150000]
 [15714658        1       48    41000]
 [15810944        1       35    20000]
 [15733883        1       47    25000]
 [15624510        1       19    19000]
 [15697686        1       29    80000]
 [15705113        1       46    23000]
 [15599081        2       45    22000]
 [15727311        2       35    60000]
 [15600575        1       45    33000]
 [15746139        1       20    86000]
 [15606274        2       26    52000]
 [15728773        1       27    58000]]


In [53]:
print(x_test)

[[15628972        1       18    82000]
 [15704987        1       32    18000]
 [15617482        1       45    26000]
 [15603246        2       27    57000]
 [15736760        2       47    49000]]


In [54]:
print(y_train)

[0 1 1 0 0 1 0 1 1 0 1 0 0 1 1 0 0 0 0 0]


In [55]:
print(y_test)

[0 0 1 0 1]


In [58]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 2:] = sc.fit_transform(x_train[:, 2:])
x_test[:, 2:] = sc.fit_transform(x_test[:, 2:])

In [59]:
print(x_train)

[[15570769        2        0        0]
 [15704583        1        1        0]
 [15621083        2        1        0]
 [15804002        1       -1        0]
 [15668575        2        0        0]
 [15649487        1        1        0]
 [15598044        2        0        0]
 [15694829        2        0        3]
 [15714658        1        1        0]
 [15810944        1        0        0]
 [15733883        1        1        0]
 [15624510        1       -1       -1]
 [15697686        1        0        0]
 [15705113        1        1        0]
 [15599081        2        1        0]
 [15727311        2        0        0]
 [15600575        1        1        0]
 [15746139        1       -1        1]
 [15606274        2        0        0]
 [15728773        1        0        0]]


In [60]:
print(x_test)

[[15628972        1       -1        1]
 [15704987        1        0       -1]
 [15617482        1        1        0]
 [15603246        2        0        0]
 [15736760        2        1        0]]
